# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Jared Bailey
description: "Hi, I’m Jared. I’m an AI specialist working at the intersection of AI, edge computing, and robotics. This portfolio features projects I’ve undertaken and continue to build on. Feel free to reach out if you’d like to connect."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: AI, Edge Device & Robotics <span style="color:#f58506"> Portfolio </span>
location: "Durham, NC"
resume_url: /docs/Jared L Bailey Resume 20260120.pdf
avatar_image: /img/Jared Square.jpeg

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/jared-l-bailey-mba-cpcu-are/" # Add your linkedln handle
github: "https://github.com/JaredBaileyDuke"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/





